### ISSUE TITLE
FGD: Capitalizing flags or choices types breaks syntax highlighting

### ISSUE THREAD

**Issue by Luke18033** [StefanH-AT/Source-Engine-VSCode-Extension#104]
If a `flags` or `choices` type keyvalue has its type capitalized (as `Flags`/`Choices` or any other combination), the syntax highlighting will break for the rest of the file or until another one of these keyvalues with the type in lowercase. This causes a number of sections of Left 4 Dead 2's default FGD to appear wrong:
![image](https://user-images.githubusercontent.com/19228201/224612129-0d81fedb-db2f-4dc0-94dc-66e24a0263ef.png)

**Comment by StefanH-AT** [comment]
Thanks for reporting, didn't know that's valid syntax
