### ISSUE TITLE
Are there any plans to  support  qc files of GoldSrc?

### ISSUE THREAD

**Issue by Ephemeralwanning** [StefanH-AT/Source-Engine-VSCode-Extension#106]
They may be similar to the Soure Engine qc file format.
If it is already supported, please ignore, I don't know much about the Soure Engine.

**Comment by StefanH-AT** [comment]
How do goldsource kv files differ? The syntax highlighter should be able to parse it given the syntax is similar.

In general, thie extension is for source engine formats, so I won't put any extra effort into addinz goldsrc formats

**Comment by StefanH-AT** [comment]
Github issues are not meant as a chat to help with your individual issues. I recommend you to ask such questions on the discord server https://discord.gg/BDDxkNwXWw and only when a discrete bug has been identified, an issue should be opened.
