### ISSUE TITLE
Incorrect KeyValues versioning

### ISSUE THREAD

**Issue by 13k** [StefanH-AT/Source-Engine-VSCode-Extension#110]
Valve's KeyValues format has 3 versions with very different syntaxes:

- [KeyValues](https://developer.valvesoftware.com/wiki/KeyValues)
- [KeyValues2](https://developer.valvesoftware.com/wiki/KeyValues2)
- [KeyValues3](https://developer.valvesoftware.com/wiki/KeyValues3)

The extension implements a mixture of KeyValues and KeyValues3 syntax which is incorrect for both:

- KeyValues1 doesn't support arrays `[ ... ]`
- KeyValues3's own [example](https://developer.valvesoftware.com/wiki/KeyValues3#Example) is not supported

**Comment by StefanH-AT** [comment]
You're right that my keyvalues versioning is an absolute mess. I'm going to rename the language to just "keyvalues" instead of specifying a specific version
