### ISSUE TITLE
VMT does not stand for Valve Material Type

### ISSUE THREAD

**Issue by vrad-exe** [StefanH-AT/Source-Engine-VSCode-Extension#111]
This extension (along with many other community tools) currently refers to `.vmt` files with the somewhat strange sounding name of *Valve Material Type*, but it should actually just be calling the format *Valve Material*.

According to [Valve's original SDK documentation](https://web.archive.org/web/20080324114324/http://www.valve-erc.com/srcsdk/Materials/materials_creation.html), VMT officially stands for *Valve Material*. The specific name *Valve Material Type* seems to have come about as a result of a VDC editor [randomly changing this as part of a large page rewrite](https://developer.valvesoftware.com/w/index.php?title=VMT&diff=60212&oldid=60189). Given that the editor provided no source for this, and I cannot find that name being used in any official place (SDKs, old docs, the tools themselves, etc.) I am inclined to believe that *Valve Material* is the correct name for the format.

I already changed this on the VDC a while back and nobody has objected to it despite several edits being made to the page since, so it seems like most people agree with my reasoning. Feel free to correct me if I'm wrong though and this name was used somewhere officially.

**Comment by StefanH-AT** [comment]
🤓

**Comment by vrad-exe** [comment]
If I changed this myself and made a pull request would you accept it

**Comment by StefanH-AT** [comment]
You're right, that wasn't mature of me. I'll sort this out in 1.1.0
