### ISSUE TITLE
Color Themes overriding syntax highlights.

### ISSUE THREAD

**Issue by henkeswe** [StefanH-AT/Source-Engine-VSCode-Extension#28]
When enabling my color theme it overwrites some of the highlights:
![yILhujuEFG](https://user-images.githubusercontent.com/3287378/139782011-eb6b01df-37e4-4258-af4a-8fbb15a5e470.gif)

There's another extension called "Valve KeyValue Files Support" which does not have this issue:
![Xw7T0AXRFr](https://user-images.githubusercontent.com/3287378/139782098-610ba8cf-2cfe-4c34-9515-c099a3badce9.gif)

**Comment by StefanH-AT** [comment]
Can you send me that theme?

**Comment by StefanH-AT** [comment]
The extension simply says "this is an attribute", "this is a struct"... 

The theme can then interpret those semantic tokens however it wants

**Comment by henkeswe** [comment]
It's nothing special, but sure
[test.theme.zip](https://github.com/StefanH-AT/Source-Engine-VSCode-Extension/files/7489441/test.theme.zip)

**Comment by StefanH-AT** [comment]
Your theme does not support semantic tokens. Find out how to enable it [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes)
