### ISSUE TITLE
Block comments do not work in qc

### ISSUE THREAD

**Issue by xDShot** [StefanH-AT/Source-Engine-VSCode-Extension#53]
Currently the extension doesn't support it

![image](https://user-images.githubusercontent.com/4261659/159162934-f0bc9027-f53e-4f10-ad7c-5b5c31af2fbf.png)

**Comment by StefanH-AT** [comment]
Fixed in version 0.3.4

**Comment by xDShot** [comment]
That was fast, thanks :)
