### ISSUE TITLE
$rimlightboost incorrectly labelled as using Integer values instead of float values

### ISSUE THREAD

**Issue by xChillax** [StefanH-AT/Source-Engine-VSCode-Extension#59]
$rimlightboost parameter in VMTs seems to give you a warning about not using integer values, however, it actually supports floating numbers.

![image](https://user-images.githubusercontent.com/6830124/162274645-c5c49274-e4fa-4761-b44c-ea6150bd1850.png)

**Comment by StefanH-AT** [comment]
Fixed in v0.3.5
