### ISSUE TITLE
Valve QC integers and floats matches as strings

### ISSUE THREAD

**Issue by LoveRenamon** [StefanH-AT/Source-Engine-VSCode-Extension#63]
Hey, migrated today from atom to VSCode due I/O performace issues, so I've been here, thank you for the extension. I've seens is more powerful and handy than atom's counterpart

I've found that macros, anything that preceed a minus signal mathes wrong syntax color _(same as string, i think?)_ so everything is tinted as the same color
![2022-06-10-150818_1920x1039_scrot](https://user-images.githubusercontent.com/9941414/173126260-51de8d3c-b5d7-4b67-909d-4e2f5618fec7.png)

I've been keep maintance of a [local version](https://github.com/LoveRenamon/language-qc) for my atom, forked from [CosignCosine/language-qc](https://github.com/CosignCosine/language-qc) that matches with different syntaxes, but as i've seen I did a totaly different thing
![2022-06-10-150738_1920x1039_scrot](https://user-images.githubusercontent.com/9941414/173126236-b3379f95-ee02-42bc-9053-bbe89be01aca.png)

Soon as understand how VSCode works I wish to contribute to Valve's QC, VMT and probably DMX formats.

**Comment by StefanH-AT** [comment]
Thanks for the bug report. I can fix that

**Comment by StefanH-AT** [comment]
QC variable (or macro) syntax is added in #64

**Comment by StefanH-AT** [comment]
Negative numbers is fixed in #65

**Comment by StefanH-AT** [comment]
Does this resolve all your issues?

**Comment by LoveRenamon** [comment]
hello, thank you for the fast response it mostly fixes. 
floats starting with a a dot still matches with a different color _(as string I think?)_ if add a zero it matches as should be.  
![2022-06-10-185340_1920x1059_scrot](https://user-images.githubusercontent.com/9941414/173156005-aeb88fb8-6179-4693-a01b-e8ce936c0c34.png) 

If you have no plans to support this syntax I'm okay if you wish close this issue

**Comment by LoveRenamon** [comment]
I did for the #69, please review if looks good to be merged

**Comment by LoveRenamon** [comment]
hey thank you;
I got busy so i cant made your requested changes. [51933f0](https://github.com/StefanH-AT/Source-Engine-VSCode-Extension/commit/51933f080bf6534e3643ddf95666d9e66ace5a13) does fix all issues;

However, you added the syntax to variables inside quoted strings, what QC doesn't support.
I'm closing this since the subject of this issue was fixed already.
Again, thank you
