### ISSUE TITLE
"Invalid matrix format" on $phongfresnelranges

### ISSUE THREAD

**Issue by WereTech** [StefanH-AT/Source-Engine-VSCode-Extension#74]
It claims to be in an incorrect format, but isn't. "$phongfresnelranges" "[.5 .5 1]" (This is a default file in TF2 and not a custom one)
![image](https://i.imgur.com/kpLhL6l.png)

I've also noticed that in this issue and the $color issue I posted previously, the quotes are sort of messing with this? When I removed the quotes it goes away. However at the same time WITH quotes, it will be made valid when I go from another file in VSC back to the file containing the phong parameter. (The $color parameter needs quotes so it's exempt from this case.) It's very strange, maybe something wrong with Intellisense? The quotes are needed because of spaces in the parameter so this is not optional.

**Comment by StefanH-AT** [comment]
I think both of the issues you reported come from the multi-file issues I've been having for a while. These have been way over-due to fix so I'm going to look into that now

**Comment by StefanH-AT** [comment]
Should be fixed in 0.4.0. Reopen if there are any more issues
