### ISSUE TITLE
Incomplete HammerAddons FGD tags support

### ISSUE THREAD

**Issue by Luke18033** [StefanH-AT/Source-Engine-VSCode-Extension#99]
There currently seems to be some support for HammerAddons tags, but it's very limited. Single tags on keyvalues and I/O will be highlighted blue, but using multiple tags or inverted tags will cause the surrounding coloring to break.
![image](https://user-images.githubusercontent.com/19228201/224507157-bc72a4e5-f4f9-417f-b9d4-990da474a0ac.png)

For `spawnflags` and `choices` type keyvalues it's worse, adding the FGD tags at the end of the line will break coloring for the *entire rest of the file* past where the tag is located.
![image](https://user-images.githubusercontent.com/19228201/224507262-1f1e989e-815d-472e-aae0-a933753661e4.png)

For reference, the full list of supported features can be found [here](https://github.com/TeamSpen210/HammerAddons/wiki/Unified-FGD)

**Comment by StefanH-AT** [comment]
I've been wanting to rewrite the FGD syntax highlighting for a while since it was way too rigid and was easily broken. Just pushed an update that should fix the issues you mentioned. (0.10.3)

Let me know if there are any more problems. If there aren't, feel free to close!

**Comment by Luke18033** [comment]
Seems to all be working as expected now! One more thing is you might want to change the parameters of the `appliesto()` helper to be colored dark blue since those are also FGD tags, but not doing that doesn't break anything.
